# ─────────────────────────────────────────────
# Orbiscreen - Android Gradle Properties
# https://github.com/shadow-x78/orbiscreen
# ─────────────────────────────────────────────

# ── JVM ──
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# ── AndroidX ──
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=35

# ── Kotlin ──
kotlin.code.style=official

# ── Resources ──
android.nonTransitiveRClass=true
